spring.application.name=JobMarket

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jobmarket}
spring.datasource.username=${DB_USERNAME:jobmarket}
spring.datasource.password=${DB_PASSWORD:jobmarket}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true